### ISSUE TITLE
Mac: got "node\r: No such file or directory" 

### ISSUE THREAD

**Issue by glebmachine** [dutchenkoOleg/node-w3c-validator#13]
I have got this error when running on a Mac:
```
./node_modules/.bin/node-w3c-validator 
> env: node\r: No such file or directory
```

But, on windows everything works fine

**Comment by dutchenkoOleg** [comment]
Hello @glebmachine !
I had just change line ending in `*.js` files.
Can you try last version on npm `@1.6.4` - it should resolve your problem.
Keep me in touch please.

**Comment by glebmachine** [comment]
@dutchenkoOleg works like a charm)
Thank you!
