### ISSUE TITLE
<img> loading attribute 

### ISSUE THREAD

**Issue by What1s1ove** [dutchenkoOleg/node-w3c-validator#14]
Hi everyone!
I get the error "Attribute “loading” not allowed on element “img” at this point.", but this is already part of the standard
I can fix this using the "suppressErrors: ["Attribute “loading” not allowed on element “img” at this point."]" rule in my package.json but I do not want to clutter this 😤

Any ideas on how to fix this? Thanks 🙂

Ps. validator.w3.org allows it

**Comment by dutchenkoOleg** [comment]
Hi!
I need more time to sort out this problem(
In the online check of the validator itself, the test is passed with the image `loading` attribute.
So far, suppressing is the only solution to the problem.

**Comment by What1s1ove** [comment]
Awesome!
Thank you @dutchenkoOleg ❤️

**Comment by What1s1ove** [comment]
@dutchenkoOleg , I updated package, but I still get an error ☹️
<img width="551" alt="изображение" src="https://user-images.githubusercontent.com/42296182/100092431-b5fd1e00-2e5e-11eb-8db9-647d195aaa56.png">

**Comment by dutchenkoOleg** [comment]
Just published
https://github.com/dutchenkoOleg/node-w3c-validator/releases/tag/2.0.1

Try this

```bash
# should be 2.0.1
npm i node-w3c-validator@latest
```
