### ISSUE TITLE
Unexpected token ? in JSON at position 7

### ISSUE THREAD

**Issue by SineYlo** [dutchenkoOleg/node-w3c-validator#18]
What day am I already fighting, and I can not understand why this module does not start…
**The command in package.json is like this:**
```
"html-check": "node-w3c-validator -i src/**/*.html -f lint -b 500"
```
**It gives an error like this when running the command:**
```
$ npm run html-check
> project-name@1.0.0 html-check
> node-w3c-validator -i src/**/*.html -f lint -b 500
✖ An error occurred while processing validator execution!
Unexpected token � in JSON at position 7
```
I read the last issues there, one of the answers says that if there are special characters in the file name, then there may be errors.  
I checked both with and without them, it still does not work.

**Comment by yunusga** [comment]
@SineYlo try increase `-b ` to `1024` or `2048`

**Comment by SineYlo** [comment]
@yunusga 
Unfortunately, it didn't help. 
I even deleted all the other html files and left only index.html in the src folder.
**As a result, I used the following command:**
```
"html-check": "node-w3c-validator -i src/index.html -f lint -b 2048"
```
The error is always the same ...

**Comment by yunusga** [comment]
@SineYlo show your `index.html`, node and node-w3c-validator versions

**Comment by SineYlo** [comment]
@yunusga 
Should I insert all the html code from the template here? He's just not small.
node — v16.13.0
node-w3c-validator — 2.0.1

**Comment by yunusga** [comment]
@SineYlo
Super strange, i have same configuration and get `√ node-w3c-validator - no errors`.
Show full system path to tested files

Did you install the "Java"?

**Comment by SineYlo** [comment]
@yunusga 
Whoa. I certainly did not notice this ...
Now I'll try to install it!
If everything goes well, I will close the issue.

**Comment by yunusga** [comment]
@SineYlo
If the problem was in Java, do not close the issue. I will make a PR with an output message about the need to install Java

**Comment by SineYlo** [comment]
@yunusga 
Indeed, when Java put everything worked :D
Of course, putting Java for the sake of one module is certainly strange, but oh well
Probably, it will not be possible to do this module without it

**Comment by yunusga** [comment]
@SineYlo Job done https://github.com/dutchenkoOleg/node-w3c-validator/pull/19, waiting for approval.

**Comment by dutchenkoOleg** [comment]
@yunusga @SineYlo - thanks for your collaboration!
PR is merged and new version is published on NPM
