### ISSUE TITLE
Node sdout buffer size limits (stdout being truncated)

### ISSUE THREAD

**Issue by yunusga** [dutchenkoOleg/node-w3c-validator#7]
### Problem
If we have many templates, some times happens #3, `!!! OUTPUT ERROR` or `Unexpected end of JSON input` errors. This is [child_process stdout being truncated](https://github.com/nodejs/node/issues/19218).

### Solution
If increase buffer size in `lib/validator.js` with option `{ maxBuffer: 1024 * 500 }` all works.

```js
// console.log(execPath.join(' '));
exec(execPath.join(' '), { maxBuffer: 1024 * 500 }, function (err, stdout, stderr) {
    let output = stdout;
    // ...
```

### Proposal
Add option for setup `maxBuffer` if needed.

**Comment by dutchenkoOleg** [comment]
@yunusga, thats great!  Thank you very much. I will add your improvement in a few days. Or you can send yout own PR

**Comment by yunusga** [comment]
@dutchenkoOleg, ok, i'll send PR this Sunday.
