### ISSUE TITLE
Unexpected Token W in JSON at position 0

### ISSUE THREAD

**Issue by mearleycf** [dutchenkoOleg/node-w3c-validator#9]
I've tried running both of the following commands, getting the same error: 

```
AEManager/tng-next-generation/ui.apps/src/main/content/jcr_root on  develop [⇣$!?]
➜ node-w3c-validator -i ./**/*.html -f html -o ./reports/result.html -s
⠙ node-w3c-validator - processing ...
Unexpected token W in JSON at position 0

AEManager/tng-next-generation/ui.apps/src/main/content/jcr_root on  develop [⇣$!?] took 4s
➜ node-w3c-validator -i . -f html -o ~/result.html -s
⠋ node-w3c-validator - processing ...
Unexpected token W in JSON at position 0
```
I want to run the validator on all html files in all sub-directories of jcr_root, which is why I assumed ./**/*.html would work. What am I doing wrong here?

**Comment by yunusga** [comment]
Need listing of your directory `jcr_root`. I think some file has special symbols in name.

**Comment by dutchenkoOleg** [comment]
Closed for now.
@mearleycf feel free to re-open issue if still need
